services:
  nginx:
    image: nginx:1.25-alpine
    platform: linux/amd64
    container_name: nginx
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "40MB"

  api1: &api
    image: rinha-fastapi:latest
    build: .
    platform: linux/amd64
    hostname: api1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "110MB"

  api2:
    <<: *api
    hostname: api2
    platform: linux/amd64
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2

  redis:
    image: redis:7.2-alpine
    platform: linux/amd64
    container_name: redis
    command: redis-server --save "" --appendonly no
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "80MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true